version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.4.0
    branches:
      only:
        - master
    steps:
      - checkout
      - run:  sudo npm cache clean -f 
      - run:  sudo npm update -g 
      - run:  sudo npm install --unsafe-perm -g @angular/cli @angular/compiler-cli typescript node-sass
      - run:  npm install
      - run:  npm test 
