version: 2
jobs:
  build:  
    docker: 
      - image: circleci/node:8.4 
    working_directory:  ~/repo 
    steps:
      - checkout 
      - run: 
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      # Download cache dependencies 
      - restore_cache:
        keys: dependency-cache-{{checksum "package.json"}}
      - run:  
        name: npm install 
        command: npm install 


