version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.4.0
    branches:
      only:
        - master
    steps:
      - checkout
      - run:  sudo rm -rf /usr/local/lib/node_modules
      - run:  sudo npm install -g npm
      - run:  npm install
      - run:  npm test 
