version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:  sudo npm install -g npm@latest
      - run:  npm install
           